# Generated by Django 5.0.4 on 2024-05-09 16:42

import pong.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PongRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=pong.models.generate_unique_code, max_length=10, unique=True)),
                ('players_id', models.JSONField()),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_limit', models.IntegerField(default=2)),
                ('left_paddle_position', models.IntegerField(default=150)),
                ('right_paddle_position', models.IntegerField(default=150)),
                ('pause', models.BooleanField(default=False)),
                ('restart', models.BooleanField(default=False)),
            ],
        ),
    ]
